---
title: "Esophogus-Microbiome-Cancer"
site: workflowr::wflow_site
output:
  workflowr::wflow_html:
    toc: false
editor_options:
  chunk_output_type: console
---

Welcome to our research website.


## Data Pre-Processing

*[NCI-UMD Data Process](data_processing_nci_umd.html)

*[TCGA Data Process](data_processing_tcga.html)

*[Sample IDs with Abundances](ids_abundance_misc.html)

*[Testing replication](test-of-replication.html)

*[Waterfall Plots](waterfall-plot.html)

*[RNAscope test](data-check-for-RNAscope.html)

## Abundance Data

Violin plots with abundance of each bacteria across samples with Barretts history.

*[Violin plots for bacterial abundance by Barretts samples](species-sample-type-combined.html)

The following pages give a variety of heatmaps w/ dendrograms that help describe the differences in OTU abundance across groups.

*[Genera Level Heatmaps with Dendrograms](slide-figures-heatmaps-dendrograms-updates.html)

*[Species Level Heatmaps with Dendrograms](heatmaps-dendrograms-species-level.html)

The following page helps describe the relationship between Fuso (and other OTUs) and tumor stage.

* Is fuso associated with tumor stage in either data set? Does X bacteria predict stage? Multivariable w/ age, sex, BMI, history of Barrett's

*[Ordered Logit Model Results](ordered-logit-model.html)

## Analyses

Bag-of-Genes Analyses

*[PICRUSt Results](picrust-analyses.html)

Results Stratified by Taxa

*[PICRUSt Results - Fusobacterium nucleatum](picrust-fuso.html)

*[PICRUSt Results - Streptococcus sanguinis](picrust-strepto.html)

*[PICRUSt Results - Campylobacter concisus](picrust-campy.html)

*[PICRUSt Results - Prevotella spp. (genus level only)](picrust-prevo.html)
