---
title: "Waterfall Plots"
output:
  workflowr::wflow_html:
    toc: true
editor_options:
  chunk_output_type: console
---

* Goal is to replicate Fisher's exact test.


```{r data, include=FALSE, echo=FALSE}
# load packages
source("code/load_packages.R")

# get data
source("code/get_cleaned_data.R")

theme_set(theme_bw())
# pal = "Sequential"
# scale_colour_discrete <-  function(palname=pal, ...){
#   scale_colour_brewer(palette=palname, ...)
# }
# scale_fill_discrete <-  function(palname=pal, ...){
#   scale_fill_brewer(palette=palname, ...)
# }

knitr::opts_chunk$set(out.width = "225%", out.height = 10)


# transform to relative abundances
phylo.data.nci.umd <- transform_sample_counts(phylo.data.nci.umd, function(x){x / sum(x)})
phylo.data.tcga.RNAseq <- transform_sample_counts(phylo.data.tcga.RNAseq, function(x){x / sum(x)})
phylo.data.tcga.WGS <- transform_sample_counts(phylo.data.tcga.WGS, function(x){x / sum(x)})

# melt data down for use
dat.16s <- psmelt(phylo.data.nci.umd)
dat.rna <- psmelt(phylo.data.tcga.RNAseq)
dat.wgs <- psmelt(phylo.data.tcga.WGS)

# fix otu formatting
dat.rna$otu2 <- "a"
dat.wgs$otu2 <- "a"
i <- 1
for(i in 1:nrow(dat.rna)){
  dat.rna$otu2[i] <- str_split(dat.rna$OTU[i], ";")[[1]][7]
}
for(i in 1:nrow(dat.wgs)){
  dat.wgs$otu2[i] <- str_split(dat.wgs$OTU[i], ";")[[1]][7]
}


# subset to fuso. nuc. only
# Streptococcus sanguinis 
# Campylobacter concisus
# Prevotella spp.

dat.16s <- filter(
  dat.16s,
  OTU %in% c(
    "Fusobacterium_nucleatum",
    unique(dat.16s$OTU[dat.16s$OTU %like% "Streptococcus_"]),
    unique(dat.16s$OTU[dat.16s$OTU %like% "Campylobacter_"]),
    "Prevotella_melaninogenica")
)
dat.rna <- filter(
  dat.rna,
  otu2 %in% c(
    "Fusobacterium nucleatum",
    "Streptococcus sanguinis",
      "Streptococcus oralis",
      "Streptococcus mitis", 
      "Streptococcus pneumoniae", 
      "Streptococcus parasanguinis", 
      "Streptococcus salivarius",
    "Campylobacter concisus",
    "Prevotella melaninogenica")
)
dat.wgs <- filter(
  dat.wgs,
  otu2 %in% c(
    "Fusobacterium nucleatum",
    "Streptococcus sanguinis",
      "Streptococcus oralis",
      "Streptococcus mitis", 
      "Streptococcus pneumoniae", 
      "Streptococcus parasanguinis", 
      "Streptococcus salivarius",
    "Campylobacter concisus",
    "Prevotella melaninogenica")
)

# new names
dat.16s$OTU1 <- factor(
  dat.16s$OTU,
  levels = c(
    "Fusobacterium_nucleatum",
    "Streptococcus_dentisani:Streptococcus_infantis:Streptococcus_mitis:Streptococcus_oligofermentans:Streptococcus_oralis:Streptococcus_pneumoniae:Streptococcus_pseudopneumoniae:Streptococcus_sanguinis",
    "Campylobacter_rectus:Campylobacter_showae",
    "Prevotella_melaninogenica"
  ),
  labels = c(
    "Fusobacterium nucleatum",
    "Streptococcus sanguinis",
    "Campylobacter concisus",
    "Prevotella melaninogenica"
  )
)
dat.rna$OTU1 <- factor(
  dat.rna$otu2,
  levels = c(
    "Fusobacterium nucleatum",
    "Streptococcus sanguinis",
    "Campylobacter concisus",
    "Prevotella melaninogenica"),
  labels = c(
    "Fusobacterium nucleatum",
    "Streptococcus sanguinis",
    "Campylobacter concisus",
    "Prevotella melaninogenica")
)

dat.wgs$OTU1 <- factor(
  dat.wgs$otu2,
  levels = c(
    "Fusobacterium nucleatum",
    "Streptococcus sanguinis",
    "Campylobacter concisus",
    "Prevotella melaninogenica"),
  labels = c(
    "Fusobacterium nucleatum",
    "Streptococcus sanguinis",
    "Campylobacter concisus",
    "Prevotella melaninogenica")
)

# rename bacteria
dat.16s$OTU <- factor(
  dat.16s$OTU,
  levels = c(
    "Fusobacterium_nucleatum",
    "Streptococcus_dentisani:Streptococcus_infantis:Streptococcus_mitis:Streptococcus_oligofermentans:Streptococcus_oralis:Streptococcus_pneumoniae:Streptococcus_pseudopneumoniae:Streptococcus_sanguinis",
    "Campylobacter_rectus:Campylobacter_showae",
    "Prevotella_melaninogenica"
  ),
  labels = c(
    "Fusobacterium nucleatum",
    "Streptococcus spp.",
    "Campylobacter concisus",
    "Prevotella melaninogenica"
  )
)
dat.rna$OTU <- factor(
  dat.rna$otu2,
  levels = c(
    "Fusobacterium nucleatum",
    "Streptococcus sanguinis",
      "Streptococcus oralis",
      "Streptococcus mitis", 
      "Streptococcus pneumoniae", 
      "Streptococcus parasanguinis", 
      "Streptococcus salivarius",
    "Campylobacter concisus",
    "Prevotella melaninogenica"),
  labels = c(
    "Fusobacterium nucleatum",
    "Streptococcus spp.",
      "Streptococcus spp.",
      "Streptococcus spp.", 
      "Streptococcus spp.", 
      "Streptococcus spp.", 
      "Streptococcus spp.",
    "Campylobacter concisus",
    "Prevotella melaninogenica")
)

dat.wgs$OTU <- factor(
  dat.wgs$otu2,
  levels = c(
    "Fusobacterium nucleatum",
    "Streptococcus sanguinis",
      "Streptococcus oralis",
      "Streptococcus mitis", 
      "Streptococcus pneumoniae", 
      "Streptococcus parasanguinis", 
      "Streptococcus salivarius",
    "Campylobacter concisus",
    "Prevotella melaninogenica"),
  labels = c(
    "Fusobacterium nucleatum",
    "Streptococcus spp.",
      "Streptococcus spp.",
      "Streptococcus spp.", 
      "Streptococcus spp.", 
      "Streptococcus spp.", 
      "Streptococcus spp.",
    "Campylobacter concisus",
    "Prevotella melaninogenica")
)



# make tumor vs normal variable
dat.16s$tumor.cat <- factor(dat.16s$tissue, levels=c("BO", "N", "T"), labels = c("Non-Tumor", "Non-Tumor", "Tumor"))
dat.rna$tumor.cat <- factor(dat.rna$SampleType_Level2, levels=c("Normal", "Tumor"), labels = c("Non-Tumor", "Tumor"))
dat.wgs$tumor.cat <- factor(dat.wgs$SampleType_Level2, levels=c("Normal", "Tumor"), labels = c("Non-Tumor", "Tumor"))

# dataset id
dat.16s$source <- "16s"
dat.rna$source <- "rna"
dat.wgs$source <- "wgs"

# plotting ids
dat.16s$X <- paste0(dat.16s$source, "-", dat.16s$tumor.cat)
dat.rna$X <- paste0(dat.rna$source, "-", dat.rna$tumor.cat)
dat.wgs$X <- paste0(dat.wgs$source, "-", dat.wgs$tumor.cat)

# relabel as (0/1) for analysis
dat.16s$tumor <- as.numeric(factor(dat.16s$tissue, levels=c("BO", "N", "T"), labels = c("Non-Tumor", "Non-Tumor", "Tumor"))) - 1
dat.rna$tumor <- as.numeric(factor(dat.rna$SampleType_Level2, levels=c("Normal", "Tumor"), labels = c("Non-Tumor", "Tumor"))) - 1
dat.wgs$tumor <- as.numeric(factor(dat.wgs$SampleType_Level2, levels=c("Normal", "Tumor"), labels = c("Non-Tumor", "Tumor"))) - 1

# presence- absence
dat.16s$pres <- ifelse(dat.16s$Abundance > 0, 1, 0)
dat.16s$pres[is.na(dat.16s$pres)] <- 0
dat.rna$pres <- ifelse(dat.rna$Abundance > 0, 1, 0)
dat.rna$pres[is.na(dat.rna$pres)] <- 0
dat.wgs$pres <- ifelse(dat.wgs$Abundance > 0, 1, 0)
dat.wgs$pres[is.na(dat.wgs$pres)] <- 0

# merge data
cls <- c("OTU", "OTU1", "Sample", "Abundance", "tumor.cat", "tumor", "source", "X", "pres")
mydata <- full_join(dat.16s[,cls], dat.rna[,cls])
mydata <- full_join(mydata, dat.wgs[,cls])

```


# Waterfall Plots


```{r}


plot.dat <- mydata %>%
  dplyr::group_by(OTU, source, tumor.cat) %>%
  dplyr::mutate(
    Abundance = ifelse(is.na(Abundance), 0, Abundance),
    ordered.x = order(Abundance, decreasing = T,
                      na.last = T)
  ) %>%
  dplyr::ungroup(tumor.cat) %>%
  dplyr::mutate(
    ordered.x = ifelse(tumor == 0, ordered.x+sum(tumor), ordered.x),
    
  )
```

## Fusobacterium nucleatum

```{r fuso, out.width="100%", out.height="200%"}

p <-  plot.dat %>%
  filter(OTU == "Fusobacterium nucleatum")%>%
  ggplot(aes(x = ordered.x,
                 y = Abundance,
                 group = tumor.cat,
                 color = tumor.cat))+
  geom_point() + 
  geom_segment(aes(x=ordered.x,
                   y=0,
                   xend=ordered.x,
                   yend=Abundance))+
  scale_color_manual(values = c("Non-Tumor"="black", "Tumor"="blue"), name = NULL) +
  facet_wrap(.~source, scales="free_x")
p

```

## Streptococcus spp.

```{r stre, out.width="100%", out.height="200%"}

p <-  plot.dat %>%
  filter(OTU == "Streptococcus spp.")%>%
  ggplot(aes(x = ordered.x,
                 y = Abundance,
                 group = tumor.cat,
                 color = tumor.cat))+
  geom_point() + 
  geom_segment(aes(x=ordered.x,
                   y=0,
                   xend=ordered.x,
                   yend=Abundance))+
  scale_color_manual(values = c("Non-Tumor"="black", "Tumor"="blue"), name = NULL) +
  facet_wrap(.~source, scales="free_x")
p

```

## Campylobacter concisus

```{r camp, out.width="100%", out.height="200%"}

p <-  plot.dat %>%
  filter(OTU == "Campylobacter concisus")%>%
  ggplot(aes(x = ordered.x,
                 y = Abundance,
                 group = tumor.cat,
                 color = tumor.cat))+
  geom_point() + 
  geom_segment(aes(x=ordered.x,
                   y=0,
                   xend=ordered.x,
                   yend=Abundance))+
  scale_color_manual(values = c("Non-Tumor"="black", "Tumor"="blue"), name = NULL) +
  facet_wrap(.~source, scales="free_x")
p

```

## Prevotella melaninogenica

```{r prev, out.width="100%", out.height="200%"}

p <-  plot.dat %>%
  filter(OTU == "Prevotella melaninogenica")%>%
  ggplot(aes(x = ordered.x,
                 y = Abundance,
                 group = tumor.cat,
                 color = tumor.cat))+
  geom_point() + 
  geom_segment(aes(x=ordered.x,
                   y=0,
                   xend=ordered.x,
                   yend=Abundance))+
  scale_color_manual(values = c("Non-Tumor"="black", "Tumor"="blue"), name = NULL) +
  facet_wrap(.~source, scales="free_x")
p

```